<?php
/**
 * Copyright © PART <info@part-online.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 // @codingStandardsIgnoreFile

 /** @var $block \Part\AdvLayNav\Block\LayeredNavigation\MultiSelect */
?>
<ol class="items multiselect-filter">
    <?php foreach ($block->getFilterItems() as $filterItem): ?>
        <li class="item">
            <?php if ($block->isFilterItemActive($filterItem)): ?>
                <a href="<?php echo $block->escapeUrl($block->getFilterItemRemoveUrl($filterItem)) ?>">
                    <input class="checkbox-input" type="checkbox" checked="checked"/>
                    <span class="checkbox-label"><?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?></span>
                </a>
            <?php else: ?>
                <a href="<?php echo $block->escapeUrl($block->getFilterItemUrl($filterItem)) ?>">
                    <input class="checkbox-input" type="checkbox"/>
                    <span class="checkbox-label"><?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?></span>
                </a>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ol>
