<?php
/**
 * Copyright © PART <info@part-online.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 // @codingStandardsIgnoreFile

 /** @var $block \Part\AdvLayNav\Block\LayeredNavigation\MultiSelect */
?>
<ol class="items">
    <?php foreach ($block->getFilterItems() as $filterItem): ?>
        <li class="item">
            <?php if ($block->isFilterItemActive($filterItem)): ?>
                <a href="<?php echo $block->escapeUrl($block->getFilterItemRemoveUrl($filterItem)) ?>">
                    <input type="checkbox" checked>
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                </a>
            <?php else: ?>
                <a href="<?php echo $block->escapeUrl($block->getFilterItemUrl($filterItem)) ?>">
                    <input type="checkbox">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                </a>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ol>
