<?php
/**
 * Copyright © PART <info@part-online.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 // @codingStandardsIgnoreFile

 /** @var $block \Part\AdvLayNav\Block\LayeredNavigation\RangeSlider */
?>
<?php
    $sliderId = "slider-range-" . $block->getFilterRequestVar();
    $amountId = "amount-" .  $block->getFilterRequestVar();
    $currencySymbol = $block->getCurrencySymbol();

?>
<div class="label-slider">
    <span><?php echo $block->formatValue($block->getMinValue())?></span>
    <span><?php echo $block->formatValue($block->getMaxValue())?></span>
</div>
<div id="<?php echo $sliderId ?>"></div>
<div class="slider-value">
    <div class="slider-value-item">
        <label><?php echo __('From')?>, <?php echo $currencySymbol?></label>
        <input id="<?php echo $sliderId?>-input-min" class="js-price" maxlength="9" type="text"/>
    </div>
    <div class="slider-value-item">
        <label><?php echo __('To')?>, <?php echo $currencySymbol?></label>
        <input id="<?php echo $sliderId?>-input-max" class="js-price" maxlength="9" type="text"/>
    </div>
</div>
<script>
    require( [ "advlaynav/rangeslider" ], function( rangeSlider ) {
        rangeSlider(
            <?php echo $block->getMinValue() ?>,
            <?php echo $block->getMaxValue() ?>,
            <?php echo $block->getLeftValue() ?>,
            <?php echo $block->getRightValue() ?>,
            "<?php echo $sliderId ?>",
            "<?php echo $amountId ?>",
            "<?php echo $block->getOptionsPlaceholderUrl() ?>",
            "<?php echo $block->getRemoveUrl() ?>"
        );
    } );
</script>
