<?php
/**
 * Copyright © PART <info@part-online.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

 // @codingStandardsIgnoreFile

 /** @var $block \Part\AdvLayNav\Block\LayeredNavigation\RenderLayered */
?>
<?php
    $sliderId = "slider-range-" . $block->getFilterRequestVar();
    $amountId = "amount-" .  $block->getFilterRequestVar();
?>
<ol class="items">
    <li class="item" id="<?php echo $amountId ?>"></li>
</ol>
<div id="<?php echo $sliderId ?>"></div>
<script>
    require(['advlaynav/rangeslider'], function (rangeSlider) {
        rangeSlider(
            <?php echo $block->getMinValue() ?>,
            <?php echo $block->getMaxValue() ?>,
            <?php echo $block->getLeftValue() ?>,
            <?php echo $block->getRightValue() ?>,
            "<?php echo $sliderId ?>",
            "<?php echo $amountId ?>",
            "<?php echo $block->getOptionsPlaceholderUrl() ?>",
            "<?php echo $block->getRemoveUrl() ?>"
        );
    });
</script>
